# Generated by Django 3.2.9 on 2021-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car_classification',
            name='classification',
            field=models.CharField(max_length=20),
        ),
    ]
